language: perl
sudo: false

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

services:
  - mysql

install:
  - echo $TRAVIS_PERL_VERSION
  - cpanm --notest -v Dist::Zilla
  - dzil authordeps | cpanm --quiet --notest
  - cpanm --quiet --notest --installdeps .

script:
  - dzil test
